import Link from "next/link";

import { SiteFrame } from "../../../components/site-frame";

export default function ConfirmationPage({ params }: { params: { hash: string } }) {
  return (
    <SiteFrame
      eyebrow="Confirmation receipt"
      title="Your selection has been recorded."
      lead="This hash is an anonymized confirmation token generated by the backend after the vote was written to the append-only ledger."
    >
      <section className="mx-auto w-full max-w-2xl section-panel space-y-6">
        <div className="rounded-[24px] border border-gold/25 bg-cream/80 px-5 py-5">
          <p className="text-xs font-semibold uppercase tracking-[0.28em] text-gold">Confirmation hash</p>
          <p className="mt-3 break-all font-mono text-lg text-navy">{params.hash}</p>
        </div>

        <div className="flex flex-wrap gap-3">
          <Link href="/ballot" className="button-primary">
            Return to ballot
          </Link>
          <Link href="/results" className="button-secondary">
            Public results page
          </Link>
        </div>
      </section>
    </SiteFrame>
  );
}
